server/config/routes.rb
Rails.application.routes.draw do
  resources :shifts
  devise_for :staffs, path: 'staffs', controllers: { sessions: "staffs/sessions", registrations: "staffs/registrations"}
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions", registrations: "admins/registrations"}
  resources :staff_details
  resources :admin_branches

  get '/admin/validate' => 'admin_branches#validate'
  get '/admin/stafflist' => 'admin_branches#staffList'
  get '/staff/validate' => 'staff_details#validate'
  get '/staff/companylist' => 'staff_details#companyList'
  get '/staff/branchlist' => 'staff_details#branchList'
  
  get '/admin/shiftlist' => 'admin_branches#shiftList'
  patch '/admin/staffshift' => 'staff_shifts#staffShiftPost'

  get '/staff/staffshifts' => 'staff_details#StaffShift'
  get '/staff/shiftList' => 'staff_details#shiftList'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

server/app/models/shift.rb
class Shift < ApplicationRecord
    belongs_to :admin_branch
    has_one :admin, through: :admin_branch
    has_and_belongs_to_many :staff_details
end

server/app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_shift, only: [:show, :edit, :update, :destroy]

  # GET /shifts
  # GET /shifts.json
  def index
    # @admin_branches = AdminBranch.where(admin_id: current_admin.id);
    # @shifts - Shift.where(@admin_branches)
    # @shift = Shift.@admin_branches
    @admin_branches = AdminBranch.where(admin_id: current_admin.id)
    p @admin_branches
    p @admin_branches.ids
    @shifts = Shift.where(admin_branch_id: @admin_branches.ids)
    render json: @shifts
  end

  # GET /shifts/1
  # GET /shifts/1.json
  def show
    if @shifts.admin.id != current_admin.id
      redirect_to shifts_path
    end
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
  end
  
  # GET /shifts/1/edit
  def edit
    @shifts.admin_id != current_admin.id
  end
  
  # POST /shifts
  # POST /shifts.json
  def create
    @shift = Shift.new(shift_params)
    
    # respond_to do |format|
      if @shift.save
        render json: {success: true}
        # format.html { redirect_to @shift, notice: 'Shift was successfully created.' }
        # format.json { render :show, status: :created, location: @shift }
      else
        p @shift.errors.inspect
        # format.html { render :new }
        # format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PATCH/PUT /shifts/1
  # PATCH/PUT /shifts/1.json
  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to @shift, notice: 'Shift was successfully updated.' }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @shift.destroy
    respond_to do |format|
      format.html { redirect_to shifts_url, notice: 'Shift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shift_params
      params.require(:shift).permit(:date, :time, :min_staff, :admin_branch_id)
    end
end

server/app/helpers/shifts_helper.rb
module ShiftsHelper
end

server/app/views/shifts/_form.html.erb
<%= form_with(model: shift, local: true) do |form| %>
  <% if shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
      <% shift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time %>
  </div>

  <div class="field">
    <%= form.label :min_staff %>
    <%= form.number_field :min_staff %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

server/app/views/shifts/edit.html.erb
<h1>Editing Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

server/app/views/shifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shifts</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Min staff</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= shift.date %></td>
        <td><%= shift.time %></td>
        <td><%= shift.min_staff %></td>
        <td><%= link_to 'Show', shift %></td>
        <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
        <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shift', new_shift_path %>

server/app/views/shifts/new.html.erb
<h1>New Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Back', shifts_path %>

server/app/views/shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @shift.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @shift.time %>
</p>

<p>
  <strong>Min staff:</strong>
  <%= @shift.min_staff %>
</p>

<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %>