server/config/routes.rb
Rails.application.routes.draw do
  resources :shifts
  devise_for :staffs, path: 'staffs', controllers: { sessions: "staffs/sessions", registrations: "staffs/registrations"}
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions", registrations: "admins/registrations"}
  resources :staff_details
  resources :admin_branches

  get '/admin/validate' => 'admin_branches#validate'
  get '/admin/stafflist' => 'admin_branches#staffList'
  get '/staff/validate' => 'staff_details#validate'
  get '/staff/companylist' => 'staff_details#companyList'
  get '/staff/branchlist' => 'staff_details#branchList'
  
  get '/admin/shiftlist' => 'admin_branches#shiftList'
  patch '/admin/staffshift' => 'staff_shifts#staffShiftPost'

  get '/staff/staffshifts' => 'staff_details#StaffShift'
  get '/staff/shiftList' => 'staff_details#shiftList'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

server/app/models/admin_branch.rb
class AdminBranch < ApplicationRecord
    belongs_to :admin
    has_many :staff_details
    has_many :shifts
end

server/app/controllers/admin_branches_controller.rb
class AdminBranchesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_admin_branch, only: [:show, :edit, :update, :destroy]

  def validate
    render json: {name: current_admin.name }
  end

  # GET /admin_branches.json
  def index
    @admin_branches = AdminBranch.where(admin_id: current_admin.id)
    render json: @admin_branches
  end

  # GET /admin_branches/1.json
  def show
    if @admin_branch.admin_id != current_admin.id
      redirect_to admin_branches_path
    end
    render json: @admin_branch
  end

  # GET /admin_branches/new
  def new
    @admin_branch = AdminBranch.new
  end

  # GET /admin_branches/1/edit
  def edit
    if @admin_branch.admin_id != current_admin.id
      redirect_to admin_branches_path
    end
  end

  # POST /admin_branches.json
  def create
    @admin_branch = AdminBranch.new(admin_branch_params)
    @admin_branch.admin_id = current_admin.id

    p @admin_branch
    respond_to do |format|
      if @admin_branch.save
        format.html { redirect_to @admin_branch, notice: 'Admin branch was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @admin_branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_branches/1
  # PATCH/PUT /admin_branches/1.json
  def update
      if @admin_branch.update(admin_branch_params)
        render json: {success: true}
      end
  end

  # DELETE /admin_branches/1
  # DELETE /admin_branches/1.json
  def destroy
    @admin_branch.destroy
    render json: {success: true}
  end

  def staffList
    @admin_branches = AdminBranch.where(admin_id: current_admin.id)
    @staff_details = StaffDetail.where(admin_branch_id: @admin_branches)
    render json: @staff_details
  end

  def shiftList
    @admin_branches = AdminBranch.where(admin_id: current_admin.id)
    @shifts = Shift.where(admin_branch_id: @admin_branches)
    @staff_shifts = StaffShift.where(shift_id: @shifts) 
    render json: @staff_shifts
  end

 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_branch
      @admin_branch = AdminBranch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_branch_params
      params.require(:admin_branch).permit(:name, :contact, :location)
    end

    def staff_shift_params
      params.require(:staff_shift).permit(:staff_detail_id, :shift_id)
    end
end

server/app/helpers/admin_branches_helper.rb
module AdminBranchesHelper
end

server/app/views/admin_branches/_form.html.erb
<%= form_with(model: admin_branch, local: true) do |form| %>
  <% if admin_branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_branch.errors.count, "error") %> prohibited this admin_branch from being saved:</h2>

      <ul>
      <% admin_branch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.number_field :contact %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

server/app/views/admin_branches/edit.html.erb
<h1>Editing Admin Branch</h1>

<%= render 'form', admin_branch: @admin_branch %>

<%= link_to 'Show', @admin_branch %> |
<%= link_to 'Back', admin_branches_path %>

server/app/views/admin_branches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Branches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_branches.each do |admin_branch| %>
      <tr>
        <td><%= admin_branch.name %></td>
        <td><%= admin_branch.contact %></td>
        <td><%= admin_branch.location %></td>
        <td><%= link_to 'Show', admin_branch %></td>
        <td><%= link_to 'Edit', edit_admin_branch_path(admin_branch) %></td>
        <td><%= link_to 'Destroy', admin_branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Branch', new_admin_branch_path %>
<%= link_to 'Logout', destroy_admin_session_path, method: :delete %>

server/app/views/admin_branches/new.html.erb
<h1>New Admin Branch</h1>

<%= render 'form', admin_branch: @admin_branch %>

<%= link_to 'Back', admin_branches_path %>

server/app/views/admin_branches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_branch.name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @admin_branch.contact %>
</p>

<p>
  <strong>Location:</strong>
  <%= @admin_branch.location %>
</p>

<%= link_to 'Edit', edit_admin_branch_path(@admin_branch) %> |
<%= link_to 'Back', admin_branches_path %>