server/config/routes.rb
Rails.application.routes.draw do
  resources :shifts
  devise_for :staffs, path: 'staffs', controllers: { sessions: "staffs/sessions", registrations: "staffs/registrations"}
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions", registrations: "admins/registrations"}
  resources :staff_details
  resources :admin_branches

  get '/admin/validate' => 'admin_branches#validate'
  get '/admin/stafflist' => 'admin_branches#staffList'
  get '/staff/validate' => 'staff_details#validate'
  get '/staff/companylist' => 'staff_details#companyList'
  get '/staff/branchlist' => 'staff_details#branchList'
  
  get '/admin/shiftlist' => 'admin_branches#shiftList'
  patch '/admin/staffshift' => 'staff_shifts#staffShiftPost'

  get '/staff/staffshifts' => 'staff_details#StaffShift'
  get '/staff/shiftList' => 'staff_details#shiftList'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

server/app/models/staff_detail.rb
class StaffDetail < ApplicationRecord
    belongs_to :staff
    has_one :admin_branches
    has_one :admin, through: :admin_branches
end

server/app/controllers/staff_details_controller.rb
class StaffDetailsController < ApplicationController
  before_action :authenticate_staff!
  before_action :set_staff_detail, only: [:show, :edit, :update, :destroy]

  # GET /staff_details
  # GET /staff_details.json

  def validate
    render json: {name: current_staff.id}
  end
  
  def companyList
    @admins = Admin.all
    render json: @admins
  end

  def branchList
    @branches = AdminBranch.all
    render json: @branches
  end

  def index
    @staff_details = StaffDetail.where(staff_id: current_staff.id)
    render json: @staff_details
  end

  # GET /staff_details/1
  # GET /staff_details/1.json
  def show
    if @staff_details.staff_id != current_staff.id
      redirect_to staff_details_path
    end
  end

  # GET /staff_details/new
  def new
    @staff_detail = StaffDetail.new
  end

  # GET /staff_details/1/edit
  def edit
    if @staff_details.staff_id != current_staff.id
      redirect_to staff_details_path
    end
  end

  # POST /staff_details
  # POST /staff_details.json
  def create
    @staff_detail = StaffDetail.new(staff_detail_params)
    @staff_detail.staff_id = current_staff.id

    
    # respond_to do |format|
      if @staff_detail.save
        puts "SAVED"
        render json: @staff_detail
      else
        puts "DID NOT SAVE"
        p @staff_detail.errors
      end
    # end
  end

  # PATCH/PUT /staff_details/1
  # PATCH/PUT /staff_details/1.json
  def update
      if @staff_detail.update(staff_detail_params)
        render json: {success: true}
      end
  end

  # DELETE /staff_details/1
  # DELETE /staff_details/1.json
  def destroy
    @staff_detail.destroy
    respond_to do |format|
      format.html { redirect_to staff_details_url, notice: 'Staff detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def StaffShift
    @staff = StaffDetail.where(staff_id: current_staff.id).first
    @staffshift = StaffShift.where(staff_detail_id: @staff.id)
    render json: @staffshift
  end

  def shiftList
    @shifts = Shift.all
    render json: @shifts
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff_detail
      @staff_detail = StaffDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_detail_params
      params.require(:staff_detail).permit(:name, :contact, :job_title, :employment_type, :admin_branch_id)
    end
end

server/app/helpers/staff_details_helper.rb
module StaffDetailsHelper
end

server/app/views/staff_details/_form.html.erb
<%= form_with(model: staff_detail, local: true) do |form| %>
  <% if staff_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff_detail.errors.count, "error") %> prohibited this staff_detail from being saved:</h2>

      <ul>
      <% staff_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.number_field :contact %>
  </div>

  <div class="field">
    <%= form.label :job_title %>
    <%= form.text_field :job_title %>
  </div>

  <div class="field">
    <%= form.label :employment_type %>
    <%= form.text_field :employment_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

server/app/views/staff_details/edit.html.erb
<h1>Editing Staff Detail</h1>

<%= render 'form', staff_detail: @staff_detail %>

<%= link_to 'Show', @staff_detail %> |
<%= link_to 'Back', staff_details_path %>

server/app/views/staff_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staff Details</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact</th>
      <th>Job title</th>
      <th>Employment type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staff_details.each do |staff_detail| %>
      <tr>
        <td><%= staff_detail.name %></td>
        <td><%= staff_detail.contact %></td>
        <td><%= staff_detail.job_title %></td>
        <td><%= staff_detail.employment_type %></td>
        <td><%= link_to 'Show', staff_detail %></td>
        <td><%= link_to 'Edit', edit_staff_detail_path(staff_detail) %></td>
        <td><%= link_to 'Destroy', staff_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff Detail', new_staff_detail_path %>
<%= link_to 'Sign Out', destroy_staff_session_path, method: :delete %>

server/app/views/staff_details/new.html.erb
<h1>New Staff Detail</h1>

<%= render 'form', staff_detail: @staff_detail %>

<%= link_to 'Back', staff_details_path %>

server/app/views/staff_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @staff_detail.name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @staff_detail.contact %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @staff_detail.job_title %>
</p>

<p>
  <strong>Employment type:</strong>
  <%= @staff_detail.employment_type %>
</p>

<%= link_to 'Edit', edit_staff_detail_path(@staff_detail) %> |
<%= link_to 'Back', staff_details_path %>